### PR TITLE
Breaking Coverage Site into Template

### PR DESCRIPTION
**Pull request by ryanmurakami**
This PR was inspired by comments in #41. It breaks out the coverage site markup into a separate file and uses a templating engine to render it. 

@mhdawson I used pystache to do the template rendering. Let me know if you see any issues with running this on the hardware.

### CODE REVIEW

**Comment by mhdawson** [comment]
It will probably run, but it introduces a new dependency that is not already installed by default on our CI machines.  How much does using pystache simplify the generation and can it be installed through pip ? 

We don't have pip installed yet by default on the CI machines but I think that is going to happen, so installation through pip as part  of Ansible in the future may be reasonable.

**Comment by ryanmurakami** [comment]
It is installable via pip: `pip install pystache`. I looked around for best practices around templating without an engine, but couldn't find a clean way to do it. I can revisit it if pulling pystache in is going to be too difficult.

**Comment by mhdawson** [comment]
I'm ok if @jbergstroem does not have any concerns. @jbergstroem can you chime in here.

**Comment by Trott** [comment]
Should this stay open?

**Comment by ryanmurakami** [comment]
@Trott I can resolve the conflicts. I think the PR is still relevant.

**Comment by Trott** [comment]
I believe coverage stuff is now in the main repo. Closing, but feel free to comment or re-open if you think I'm wrong about that.

**Pull request closed without merging**
