### PR TITLE
add meeting minutes

### PR DESCRIPTION
**Pull request by Trott**
Minutes from today's meeting. /cc @santigimeno @TheAlphaNerd @joaocgreis @orangemocha

### CODE REVIEW

**Comment by MylesBorins** [comment]
LGTM

**Comment by santigimeno** [comment]
LGTM

**Comment by cjihrig** [comment]
Sorry I missed this meeting - I had a family thing.

The idea about automating the process of searching through flaky tests sounds interesting. It might be useful to setup a database, and hang on to results for some period of time (I think I saw similar discussion recently about storing benchmarking results). Then it would be a lot simpler to write arbitrary queries against the data, and maybe even get a web interface setup eventually.

**Comment by cjihrig** [comment]
Even though I wasn't at this meeting, I read through the notes and LGTM

**Comment by santigimeno** [comment]
@Trott Thanks for doing this.
One question: are you opening the issue regarding the search of test results in Jenkins? I've been looking into it a little and seems feasible. The only bit that I think is missing (correct me if I'm wrong) is that the `test.tap` result of older builds is not accessible, only the one from the latest. Of course the results web page could be scraped but that seems too complicated. Could the jobs @ jenkins be configured so the `test.tap` is archived?

**Comment by joaocgreis** [comment]
LGTM

**Comment by orangemocha** [comment]
LGTM. 

I think the issue about searching tap result can be opened on this repo (I have a slight preference for this) or the build repo. In either case it should mention nodejs/build as that group currently manages our Jenkins deployment.

**Pull request merged**
