### PR TITLE
coverage: translate info into WIP scripts

### PR DESCRIPTION
**Pull request by Fishrock123**
Some things still don't work though...

I couldn't get gcov to work, and grep -o doesn't work with +/* in the
regex for me

cc @addaleax & @mhdawson

### CODE REVIEW

**Comment by addaleax** [comment]
Just for reference, the original scripts are still available at https://github.com/addaleax/node-core-coverage

**Comment by mhdawson** [comment]
I can't quite decode your title "translate info into WIP scripts".  You are trying to create scripts that can be run outside the build environment ?

**Comment by Fishrock123** [comment]
> You are trying to create scripts that can be run outside the build environment ?

@mhdawson Yes but ideally both?

Coverage is... a lot less useful unless you can also run it locally...

**Comment by mhdawson** [comment]
Agreed, my goal is to get us to "make coverage" as the way to build/run coverage and @curryKitten is working to pull more of the pieces needed for that into the core.  I'll try to catch up with him to see how far away we are on that front.

**Comment by CurryKitten** [comment]
As @mhdawson mentioned, I'm working on some additional changes which will effectively give you a coverage result from running make so a developer will be able to see what impact a code change/fix/new test has on the overall coverage result.  Next action is to add Javascript coverage into the build.

**Comment by Fishrock123** [comment]
@CurryKitten Is your work on a public repo somewhere?

**Comment by CurryKitten** [comment]
@Fishrock123 I'll push my code into my fork (https://github.com/CurryKitten/node) before I make a PR.  Should have something ready next week, but I'll let you know

**Comment by Trott** [comment]
Now that we have `make coverage`, should this be closed?

**Comment by gibfahn** [comment]
>Now that we have make coverage, should this be closed?

Seems like it, if not it can be reopened.

**Pull request closed without merging**
