### PR TITLE
coverage: update 404 stylesheet link to existing stylesheet

### PR DESCRIPTION
**Pull request by Trott**
This will hopefully resize the absurdly large logo.

### CODE REVIEW

**Comment by Trott** [comment]
bump. @nodejs/testing

**Review by cjihrig — APPROVED** [review]
I like the huge logo, but LGTM if this fixes it.

**Comment by mhdawson** [comment]
Had  not seen this one so had opened https://github.com/nodejs/nodejs.org/issues/1110.

If this fixes it for coverage, I'll do the same for benchmarking.nodejs.or.g

**Comment by Trott** [comment]
If this lands, does it automatically update coverage.nodejs.org at some point? Or does someone have to do something to make that happen?

**Comment by mhdawson** [comment]
I'm testing it out now manually, but when it lands it does automatically result in the site being updated as the updated file will be pulled when the coverage job runs.

**Review by mhdawson — APPROVED** [review]
LGTM, it resolves the issue based on my manual test.

@Trott  I'm done for today so if you have time please go ahead and land, otherwise it will go back to the broken state when the coverage job runs tonight and I'll land tomorrow.

**Pull request merged**
